### ISSUE TITLE
Your "my crates are popular" bot is broken

### ISSUE THREAD

**Issue by dylanmc** [ccmlm/BTM#2]
The downloads you're driving to your own crate aren't modulating with the day of the week like actual popular crates do -- the graph is completely flat, and each version has exactly the same number of downloads per day. Completely fails to pass my Turing test (along with wasting bandwidth).

**Comment by pro465** [comment]
there seems to be a rise of malicious behavior in the FOSS community.

first Faker, then Color, then node-ipc, then this. its almost like the people are becoming more and more malicious

**Comment by dylanmc** [comment]
Closing bugs without comment isn't very social behavior. Of course, I shouldn't be surprised, because abusing community / open source resources is downright anti-social.

**Comment by ccmlm** [comment]
@dylanmc

Because the content you mentioned has nothing to do with the logic of this library, I'm used to closing this type of problem directly. I have a careful look at the content you mentioned just now, i didn't do the behavior you mentioned. I'm a senior engineer. If I did it, I would at least know that the download times would drop at weekends, i think i am not be such an idiot. If you need any specific help from me, please supplement it.

**Comment by dylanmc** [comment]
Thanks for responding. I'm glad to hear you didn't do the download bot. Your other repository, VSDB had exactly the same behavior, so I drew conclusions. Also, since I filed this bug, the bot seems to have halted. I understand correlation ≠ causation.
